name: Collect stats

on:
  schedule:
    - cron: '1 15 * * *'
  workflow_dispatch:

jobs:
  create-and-commit-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run PowerShell Script
        run: |
          pwsh -File collect-stats.ps1
          pwsh -File rancheros-stats.ps1
        shell: pwsh

      - name: Commit stats.csv
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git commit -m "Update stats"
          git push
        shell: pwsh
